branches: 
only:
- master
language: python
python:
- '3.4'
install: pip install -r requirements.txt
script: nosetests tests
after_success: zip -r latest.zip .
before_deploy:
- mkdir -p dpl_cd_upload
- mv latest.zip dpl_cd_upload/latest.zip
deploy:
  provider: codedeploy
  access_key_id: AKIAIDJFUA6FY4AKAJ6Q
  secret_access_key:
    secure: KWRYhacjaYSNjHor3GnSB90fuvnF9mAy933C5LOOKUwqix2FCzP61cBhBY6I2IMAu7vQCW1R7/DVLKyNZOLLqlXJHIUWW784WnpEYely2j0S56tQQwhunif9SDc9lXT1tE+OYwiyg+ZGRealKGZho1m9gfyMOpfT+RjipK4XfE0=
  bucket: datamade-codedeploy
  key: latest.zip
  bundle_type: zip
  application: codedeploy-test
  deployment_group: codedeploy-test-group
  on:
    repo: datamade/codedeploy-test
